# Generated by Django 5.1.3 on 2024-11-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='docentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoDocente', models.CharField(max_length=6)),
                ('nombreDocente', models.CharField(max_length=255)),
                ('estatus', models.BooleanField()),
            ],
        ),
    ]
