# Generated by Django 5.1.3 on 2024-11-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinallp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoTicket', models.CharField(max_length=10)),
                ('descripcionTicket', models.CharField(max_length=255)),
                ('estatus', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='docentes',
        ),
    ]
