# Generated by Django 5.1.3 on 2024-11-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinallp1', '0002_tickets_delete_docentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='precioTicket',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
