# Generated by Django 5.1.3 on 2024-11-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinallp1', '0003_tickets_precioticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoTicket', models.CharField(max_length=10)),
                ('nombreTicket', models.CharField(max_length=20)),
                ('descripcionTicket', models.CharField(max_length=255)),
                ('precioTicket', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('estatus', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='tickets',
        ),
    ]
