# Generated by Django 5.1.3 on 2024-11-30 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFinallp1', '0004_ticket_delete_tickets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ticket',
            new_name='tickets',
        ),
    ]
