# Generated by Django 5.1.3 on 2024-12-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFinallp1', '0005_rename_ticket_tickets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tickets',
            new_name='ticketsalli',
        ),
    ]
