# Generated by Django 5.1.3 on 2024-12-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinallp1', '0006_rename_tickets_ticketsalli'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsalli',
            name='tipo',
            field=models.CharField(choices=[('GENERAL', 'General'), ('VIP', 'VIP'), ('ALL ACCESS', 'All Access')], default='GENERAL', max_length=20),
        ),
    ]
